/home/adaogomes.l/nequip-pyrai2md/PyRAI2MD-hiam/PyRAI2MD/Machine_Learning/NequIP.py:84: UserWarning: Use model type names as chemical symbols; to avoid this warning, please provide the full `chemical_symbols` used in config.yaml during training.
  warnings.warn(
/home/adaogomes.l/nequip-pyrai2md/PyRAI2MD-hiam/PyRAI2MD/Dynamics/Propagators/surface_hopping.py:37: RuntimeWarning: invalid value encountered in scalar power
  at, ht, dt, v, hoped, old_state, state, info = FSSH(traj_dict)
